#!/usr/bin/env node
require('dotenv').config({ path: require('path').join(__dirname, '../../../.env') })

const { v4: uuidv4 } = require('uuid')
const db = require('../db/schema')

const providers = [
  // ── Hospitales ──────────────────────────────────────────────────────────────
  {
    name: 'Jackson Memorial Hospital',
    type: 'Hospital',
    specialty: 'Level I Trauma Center',
    phone: '(305) 585-1111',
    fax: '(305) 585-6000',
    email: 'medicalrecords@jhsmiami.org',
    address: '1611 NW 12th Ave, Miami, FL 33136',
    hours: 'Mon–Fri 8:00am–4:30pm',
    portal_url: 'https://www.jacksonhealth.org',
    notes: 'Largest public hospital in Florida. Request records via Release of Information dept.',
  },
  {
    name: 'Baptist Health South Florida',
    type: 'Hospital',
    specialty: 'General Acute Care',
    phone: '(786) 596-1960',
    fax: '(786) 596-6910',
    email: 'records@baptisthealth.net',
    address: '8900 N Kendall Dr, Miami, FL 33176',
    hours: 'Mon–Fri 8:00am–5:00pm',
    portal_url: 'https://www.baptisthealth.net',
    notes: 'Records turnaround approx. 10 business days.',
  },
  {
    name: 'Broward Health Medical Center',
    type: 'Hospital',
    specialty: 'Level II Trauma Center',
    phone: '(954) 355-4400',
    fax: '(954) 355-5509',
    email: 'hieinfo@browardhealth.org',
    address: '1600 S Andrews Ave, Fort Lauderdale, FL 33316',
    hours: 'Mon–Fri 8:30am–4:30pm',
    portal_url: 'https://www.browardhealth.org',
    notes: null,
  },
  {
    name: 'Memorial Regional Hospital',
    type: 'Hospital',
    specialty: 'Level I Trauma Center',
    phone: '(954) 987-2000',
    fax: '(954) 985-6278',
    email: 'medrecords@mhs.net',
    address: '3501 Johnson St, Hollywood, FL 33021',
    hours: 'Mon–Fri 8:00am–4:00pm',
    portal_url: 'https://www.mhs.net',
    notes: 'Part of Memorial Healthcare System.',
  },
  {
    name: 'Tampa General Hospital',
    type: 'Hospital',
    specialty: 'Level I Trauma Center',
    phone: '(813) 844-7000',
    fax: '(813) 844-4493',
    email: 'roi@tgh.org',
    address: '1 Tampa General Cir, Tampa, FL 33606',
    hours: 'Mon–Fri 8:00am–4:30pm',
    portal_url: 'https://www.tgh.org',
    notes: null,
  },
  {
    name: 'AdventHealth Orlando',
    type: 'Hospital',
    specialty: 'General Acute Care',
    phone: '(407) 303-5600',
    fax: '(407) 303-5611',
    email: 'records@adventhealth.com',
    address: '601 E Rollins St, Orlando, FL 32803',
    hours: 'Mon–Fri 7:30am–4:30pm',
    portal_url: 'https://www.adventhealth.com',
    notes: null,
  },
  {
    name: 'Kendall Regional Medical Center',
    type: 'Hospital',
    specialty: 'General Acute Care',
    phone: '(305) 223-3000',
    fax: '(305) 223-3215',
    email: 'roi@kendallmed.com',
    address: '11750 Bird Rd, Miami, FL 33175',
    hours: 'Mon–Fri 8:00am–4:00pm',
    portal_url: 'https://kendallmed.com',
    notes: null,
  },

  // ── Clínicas y Especialistas ─────────────────────────────────────────────────
  {
    name: 'Florida Spine & Pain Institute',
    type: 'Specialist',
    specialty: 'Pain Management',
    phone: '(305) 441-7246',
    fax: '(305) 441-9132',
    email: 'info@floridaspinepain.com',
    address: '2601 SW 37th Ave, Suite 401, Miami, FL 33133',
    hours: 'Mon–Fri 9:00am–5:00pm',
    portal_url: null,
    notes: 'Common referral for MVA patients. Accepts LOP.',
  },
  {
    name: 'Miami Orthopedic Specialists',
    type: 'Specialist',
    specialty: 'Orthopedic Surgery',
    phone: '(305) 666-2400',
    fax: '(305) 666-8877',
    email: 'records@miamiortho.com',
    address: '7800 SW 87th Ave, Suite A-110, Miami, FL 33173',
    hours: 'Mon–Fri 8:30am–5:00pm',
    portal_url: null,
    notes: null,
  },
  {
    name: 'Advanced Neurology Associates',
    type: 'Specialist',
    specialty: 'Neurology',
    phone: '(954) 714-8900',
    fax: '(954) 714-8910',
    email: null,
    address: '4800 N Federal Hwy, Suite 300, Boca Raton, FL 33431',
    hours: 'Mon–Fri 9:00am–5:00pm',
    portal_url: null,
    notes: 'Requires referral. Turnaround 15 business days.',
  },
  {
    name: 'South Florida Chiropractic Center',
    type: 'Specialist',
    specialty: 'Chiropractic',
    phone: '(305) 559-9955',
    fax: '(305) 559-0044',
    email: 'billing@sfchiro.com',
    address: '9100 S Dadeland Blvd, Suite 1500, Miami, FL 33156',
    hours: 'Mon–Sat 8:00am–6:00pm',
    portal_url: null,
    notes: 'Accepts PIP and LOP cases.',
  },
  {
    name: 'Coastal Imaging & Radiology',
    type: 'Specialist',
    specialty: 'Diagnostic Radiology',
    phone: '(954) 566-2220',
    fax: '(954) 566-3310',
    email: 'reports@coastalimaging.com',
    address: '3000 N Federal Hwy, Fort Lauderdale, FL 33306',
    hours: 'Mon–Fri 7:00am–6:00pm, Sat 8:00am–2:00pm',
    portal_url: null,
    notes: 'MRI, CT, X-Ray. 24–48 hr report turnaround.',
  },

  // ── Ambulancias / EMS ────────────────────────────────────────────────────────
  {
    name: 'Sunstar Paramedics',
    type: 'Ambulance',
    specialty: 'Emergency Medical Transport',
    phone: '(727) 462-7590',
    fax: '(727) 464-8882',
    email: 'billing@sunstar911.com',
    address: '6500 118th Ave N, Largo, FL 33773',
    hours: '24/7 Dispatch',
    portal_url: null,
    notes: 'Primary EMS for Pinellas County.',
  },
  {
    name: 'Miami-Dade Fire Rescue',
    type: 'Ambulance',
    specialty: 'Emergency Medical Transport',
    phone: '(786) 331-5000',
    fax: '(786) 331-5050',
    email: 'mdfr.records@miamidade.gov',
    address: '9300 NW 41st St, Doral, FL 33178',
    hours: '24/7 Dispatch',
    portal_url: 'https://www.miamidade.gov/fire',
    notes: null,
  },
  {
    name: 'Broward Sheriff Fire Rescue',
    type: 'Ambulance',
    specialty: 'Emergency Medical Transport',
    phone: '(954) 765-4900',
    fax: '(954) 765-4970',
    email: 'bso.firerecords@broward.org',
    address: '2601 W Broward Blvd, Fort Lauderdale, FL 33312',
    hours: '24/7 Dispatch',
    portal_url: 'https://www.sheriff.org',
    notes: null,
  },
  {
    name: 'American Medical Response (AMR)',
    type: 'Ambulance',
    specialty: 'Emergency & Non-Emergency Transport',
    phone: '(800) 356-3333',
    fax: '(877) 774-1207',
    email: 'amrbilling@amr.net',
    address: '2821 S Parker Rd, Aurora, CO 80014',
    hours: '24/7',
    portal_url: 'https://www.amr.net',
    notes: 'Largest private ambulance provider in the US.',
  },

  // ── Aseguradoras ─────────────────────────────────────────────────────────────
  {
    name: 'State Farm Insurance',
    type: 'Insurance',
    specialty: 'Auto & Health Insurance',
    phone: '(800) 782-8332',
    fax: '(877) 627-5757',
    email: 'claims@statefarm.com',
    address: 'P.O. Box 2367, Bloomington, IL 61702',
    hours: '24/7 Claims',
    portal_url: 'https://www.statefarm.com',
    notes: 'PIP claims: use dedicated PIP line.',
  },
  {
    name: 'GEICO Insurance',
    type: 'Insurance',
    specialty: 'Auto Insurance',
    phone: '(800) 841-3000',
    fax: '(888) 483-0601',
    email: 'claims@geico.com',
    address: '5260 Western Ave, Chevy Chase, MD 20815',
    hours: '24/7 Claims',
    portal_url: 'https://www.geico.com',
    notes: null,
  },
  {
    name: 'Progressive Insurance',
    type: 'Insurance',
    specialty: 'Auto Insurance',
    phone: '(800) 776-4737',
    fax: '(440) 603-5820',
    email: 'service@progressive.com',
    address: '6300 Wilson Mills Rd, Mayfield Village, OH 44143',
    hours: '24/7 Claims',
    portal_url: 'https://www.progressive.com',
    notes: null,
  },
  {
    name: 'Allstate Insurance',
    type: 'Insurance',
    specialty: 'Auto & Home Insurance',
    phone: '(800) 255-7828',
    fax: '(877) 597-7710',
    email: 'claims@allstate.com',
    address: '2775 Sanders Rd, Northbrook, IL 60062',
    hours: '24/7 Claims',
    portal_url: 'https://www.allstate.com',
    notes: null,
  },
  {
    name: 'USAA Insurance',
    type: 'Insurance',
    specialty: 'Auto & Health Insurance',
    phone: '(800) 531-8722',
    fax: '(800) 531-8077',
    email: 'claims@usaa.com',
    address: '9800 Fredericksburg Rd, San Antonio, TX 78288',
    hours: '24/7 Claims',
    portal_url: 'https://www.usaa.com',
    notes: 'Military members and families only.',
  },
  {
    name: 'Blue Cross Blue Shield of Florida',
    type: 'Insurance',
    specialty: 'Health Insurance',
    phone: '(904) 791-6111',
    fax: '(904) 905-6638',
    email: 'provider@bcbsfl.com',
    address: '4800 Deerwood Campus Pkwy, Jacksonville, FL 32246',
    hours: 'Mon–Fri 8:00am–6:00pm',
    portal_url: 'https://www.floridablue.com',
    notes: 'Also known as Florida Blue.',
  },
  {
    name: 'United Healthcare',
    type: 'Insurance',
    specialty: 'Health Insurance',
    phone: '(866) 892-5890',
    fax: '(866) 842-3278',
    email: 'uhcprovider@uhc.com',
    address: '9900 Bren Rd E, Minnetonka, MN 55343',
    hours: 'Mon–Fri 8:00am–8:00pm',
    portal_url: 'https://www.uhcprovider.com',
    notes: null,
  },
  {
    name: 'Aetna Health Insurance',
    type: 'Insurance',
    specialty: 'Health Insurance',
    phone: '(800) 872-3862',
    fax: '(860) 273-7280',
    email: 'provider@aetna.com',
    address: '151 Farmington Ave, Hartford, CT 06156',
    hours: 'Mon–Fri 8:00am–6:00pm ET',
    portal_url: 'https://www.aetna.com',
    notes: null,
  },
  {
    name: 'Humana Health Plans',
    type: 'Insurance',
    specialty: 'Health & Medicare Insurance',
    phone: '(800) 457-4708',
    fax: '(800) 334-5159',
    email: 'provider@humana.com',
    address: '500 W Main St, Louisville, KY 40202',
    hours: 'Mon–Fri 8:00am–8:00pm ET',
    portal_url: 'https://www.humana.com',
    notes: null,
  },
]

const insert = db.prepare(`
  INSERT OR IGNORE INTO providers
    (id, name, type, specialty, phone, fax, email, address, hours, portal_url, notes)
  VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`)

let inserted = 0
let skipped  = 0

for (const p of providers) {
  const exists = db.prepare('SELECT id FROM providers WHERE name = ?').get(p.name)
  if (exists) { skipped++; console.log(`  - Omitido (ya existe): ${p.name}`); continue }

  insert.run(uuidv4(), p.name, p.type, p.specialty, p.phone, p.fax, p.email,
             p.address, p.hours, p.portal_url, p.notes)
  inserted++
  console.log(`  ✓ ${p.name}`)
}

console.log(`\n✅ ${inserted} providers insertados, ${skipped} omitidos.`)
process.exit(0)
